=== RadyaAlbasha/XML/day1/lab1&2/newemptyDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT library (books)>
<!ELEMENT books (book+)>
<!ELEMENT book (preface,parts)>
<!ELEMENT preface (#PCDATA)>
<!ELEMENT parts (part+)>
<!ELEMENT part (sections)>
<!ELEMENT sections (section+)>
<!ELEMENT section (content)>
<!ELEMENT content (paragraph+)>
<!ELEMENT paragraph EMPTY>

<!ATTLIST library location CDATA #FIXED "Nasr city" description CDATA #REQUIRED librarian CDATA #REQUIRED>
<!ATTLIST book title CDATA #REQUIRED ISBN CDATA #REQUIRED Author CDATA #REQUIRED>
<!ATTLIST part title CDATA #REQUIRED summary CDATA #REQUIRED>
<!ENTITY my_description "no description">

=== RadyaAlbasha/XML/day1/lab1&2/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE library SYSTEM "newemptyDTD.dtd">

<library location="Nasr city" description="$my_description;" librarian="Mnal">
    <books>
        <book title="meki" ISBN="1997" Author="radya">
            <preface>
                <![CDATA[
                        book' preface
                 ]]>
            </preface>
            <parts>
                <part title="" summary="">
                    <sections>
                        <section>
                            <content>
                                <paragraph/>
                            </content>
                        </section>
                    </sections>
                </part>
            </parts>
        </book>
    </books>
</library>
